services:
  database:
    image: 'postgres:latest'
    ports:
      - '5432:5432'
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_DB=cargo'
      - 'POSTGRES_PASSWORD=postgres'
    volumes:
      - './data/postgres:/var/lib/postgresql/data'
